name = "crafthead-dev"
main = "worker/index.ts"
workers_dev = true
compatibility_date = "2024-01-28"
analytics_engine_datasets = [
	{ binding = "CRAFTHEAD_ANALYTICS" }
]

[site]
bucket = "./website"

[build]
command = "wasm-pack build --release -t nodejs && wsl ./helper/morph-wasm-pack-output.sh" # required

[env.production]
name = "crafthead"
route = { pattern = "crafthead.net/*", zone_name = "crafthead.net" }
analytics_engine_datasets = [
	{ binding = "CRAFTHEAD_ANALYTICS" }
]
