name = "crafthead-dev"
main = "worker/index.ts"
workers_dev = true
compatibility_date = "2022-08-10"
kv_namespaces = [ 
         { binding = "CRAFTHEAD_PROFILE_CACHE", id = "35768ef9b3194411936efc9c81db0571", preview_id = "aaa72d6541f4427f94059a514b3a94ff" }
]

[build]
command = "wasm-pack build --release -t nodejs && ./helper/morph-wasm-pack-output.sh" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[env.production]
name = "mcavatar"
webpack_config = "webpack.prod.config.js"
route = "https://crafthead.net/*"